version: "3"
services:
  wikijs_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${WIKIJS_DB_PASS}
      POSTGRES_USER: ${WIKIJS_DB_USER}
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data

  wikijs:
    image: requarks/wiki:2
    depends_on:
      - wikijs_db
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs_db
      DB_PORT: 5432
      DB_USER: ${WIKIJS_DB_USER}
      DB_PASS: ${WIKIJS_DB_PASS}
      DB_NAME: wiki
    restart: unless-stopped
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wikijs.entrypoints=https"
      - "traefik.http.routers.wikijs.rule=Host(`wikijs.${DOMAIN_NAME_LOCAL}`)"
      - "traefik.http.services.wikijs.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
